-- Creates dns records for each section
function pps_sections(target)
  -- A records
  a("ag", target)
  a("ai", target)
  a("ar", target)
  a("bb", target)
  a("be", target)
  a("bern.be", target)
  a("bl", target)
  a("bs", target)
  a("fr", target)
  a("ge", target)
  a("gl", target)
  a("gr", target)
  a("ju", target)
  a("lu", target)
  a("ne", target)
  a("nw", target)
  a("ow", target)
  a("sg", target)
  a("sh", target)
  a("so", target)
  a("stadt.zh", target)
  a("steinhausen", target)
  a("sz", target)
  a("tg", target)
  a("ti", target)
  a("ur", target)
  a("vd", target)
  a("vs", target)
  a("winterthur.zh", target)
  a("zg", target)
  a("zh", target)
  a("zs", target)

  -- MX records
  mx("ag", target, 10)
  mx("ai", target, 10)
  mx("ar", target, 10)
  mx("bb", target, 10)
  mx("be", target, 10)
  mx("bern.be", target, 10)
  mx("bl", target, 10)
  mx("bs", target, 10)
  mx("fr", target, 10)
  mx("ge", target, 10)
  mx("gl", target, 10)
  mx("gr", target, 10)
  mx("ju", target, 10)
  mx("lu", target, 10)
  mx("ne", target, 10)
  mx("nw", target, 10)
  mx("ow", target, 10)
  mx("sg", target, 10)
  mx("sh", target, 10)
  mx("so", target, 10)
  mx("stadt.zh", target, 10)
  mx("steinhausen", target, 10)
  mx("sz", target, 10)
  mx("tg", target, 10)
  mx("ti", target, 10)
  mx("ur", target, 10)
  mx("vd", target, 10)
  mx("vs", target, 10)
  mx("winterthur.zh", target, 10)
  mx("zg", target, 10)
  mx("zh", target, 10)
  mx("zs", target, 10)
end
